spring:
  application:
    name: companies-crud-fallback
  profiles:
    active: default
  config:
    import: "optional:configserver:http://localhost:7777"
server:
  servlet:
    context-path: /companies-crud-fallback
  port: 8787
eureka:
  instance:
    instance-id: "${spring.application.name}:${random.value}"
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

