spring:
  application:
    name: companies-crud-fallback
  profiles:
    active: default
  config:
    import: "optional:configserver:${CONFIG_SERVER_HOST}"
server:
  servlet:
    context-path: /companies-crud-fallback
  port: 8787
eureka:
  instance:
    instance-id: "${spring.application.name}:${random.value}"
  client:
    service-url:
      defaultZone: ${EUREKA_URL}

