spring:
  application:
    name: gateway
  profiles:
      active: eureka-on-cb
server:
  port: 4040
eureka:
  client:
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    com.netflix.discovery: DEBUG
