spring:
  application:
    name: gateway
profiles:
  profile: default
server:
  port: 4040
eureka:
  client:
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:8761/eureka/
