spring:
  application:
    name: gateway
  profiles:
      active: oauth2
server:
  port: 4040
eureka:
  client:
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_URL}
logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    com.netflix.discovery: DEBUG
